import type { CurriculumOutcomeMetadata } from "./types";

const grade8Source = {
  title: "2018 Fen Bilimleri Dersi Öğretim Programı",
  url: "https://mufredat.meb.gov.tr/Dosyalar/201812312311937-FEN%20B%C4%B0L%C4%B0MLER%C4%B0%20%C3%96%C4%9ERET%C4%B0M%20PROGRAMI2018.pdf",
  documentName: "FEN BİLİMLERİ ÖĞRETİM PROGRAMI 2018.pdf",
} as const;

export const grade8CurriculumMetadata: readonly CurriculumOutcomeMetadata[] = [
  // ==========================================
  // ÜNİTE 1: Mevsimler ve İklim (F.8.1)
  // ==========================================
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.1",
    unitName: "Mevsimler ve İklim",
    outcomeCode: "F.8.1.1.1",
    outcomeDescription: "Mevsimlerin oluşumuna yönelik tahminlerde bulunur.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.1",
    unitName: "Mevsimler ve İklim",
    outcomeCode: "F.8.1.2.1",
    outcomeDescription: "İklim ve hava olayları arasındaki farkı açıklar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.1",
    unitName: "Mevsimler ve İklim",
    outcomeCode: "F.8.1.2.2",
    outcomeDescription: "İklim biliminin (klimatoloji) bir bilim dalı olduğunu ve bu alanda çalışan uzmanlara iklim bilimci (klimatolog) adı verildiğini söyler.",
    officialHours: null,
    source: grade8Source,
  },

  // ==========================================
  // ÜNİTE 2: DNA ve Genetik Kod (F.8.2)
  // ==========================================
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.2",
    unitName: "DNA ve Genetik Kod",
    outcomeCode: "F.8.2.1.1",
    outcomeDescription: "Nükleotid, gen, DNA ve kromozom kavramlarını açıklayarak bu kavramlar arasında ilişki kurar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.2",
    unitName: "DNA ve Genetik Kod",
    outcomeCode: "F.8.2.1.2",
    outcomeDescription: "DNA’nın yapısını model üzerinde gösterir.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.2",
    unitName: "DNA ve Genetik Kod",
    outcomeCode: "F.8.2.1.3",
    outcomeDescription: "DNA’nın kendini nasıl eşlediğini ifade eder.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.2",
    unitName: "DNA ve Genetik Kod",
    outcomeCode: "F.8.2.2.1",
    outcomeDescription: "Kalıtım ile ilgili kavramları tanımlar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.2",
    unitName: "DNA ve Genetik Kod",
    outcomeCode: "F.8.2.2.2",
    outcomeDescription: "Tek karakter çaprazlamaları ile ilgili problemler çözerek sonuçlar hakkında yorum yapar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.2",
    unitName: "DNA ve Genetik Kod",
    outcomeCode: "F.8.2.2.3",
    outcomeDescription: "Akraba evliliklerinin genetik sonuçlarını tartışır.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.2",
    unitName: "DNA ve Genetik Kod",
    outcomeCode: "F.8.2.3.1",
    outcomeDescription: "Örneklerden yola çıkarak mutasyonu açıklar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.2",
    unitName: "DNA ve Genetik Kod",
    outcomeCode: "F.8.2.3.2",
    outcomeDescription: "Örneklerden yola çıkarak modifikasyonu açıklar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.2",
    unitName: "DNA ve Genetik Kod",
    outcomeCode: "F.8.2.3.3",
    outcomeDescription: "Mutasyonla modifikasyon arasındaki farklar ile ilgili çıkarımda bulunur.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.2",
    unitName: "DNA ve Genetik Kod",
    outcomeCode: "F.8.2.4.1",
    outcomeDescription: "Canlıların yaşadıkları çevreye uyumlarını gözlem yaparak açıklar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.2",
    unitName: "DNA ve Genetik Kod",
    outcomeCode: "F.8.2.5.1",
    outcomeDescription: "Genetik mühendisliğini ve biyoteknolojiyi ilişkilendirir.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.2",
    unitName: "DNA ve Genetik Kod",
    outcomeCode: "F.8.2.5.2",
    outcomeDescription: "Biyoteknolojik uygulamalar kapsamında oluşturulan ikilemlerle bu uygulamaların insanlık için yararlı ve zararlı yönlerini tartışır.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.2",
    unitName: "DNA ve Genetik Kod",
    outcomeCode: "F.8.2.5.3",
    outcomeDescription: "Gelecekteki genetik mühendisliği ve biyoteknoloji uygulamalarının neler olabileceği hakkında tahminde bulunur.",
    officialHours: null,
    source: grade8Source,
  },

  // ==========================================
  // ÜNİTE 3: Basınç (F.8.3)
  // ==========================================
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.3",
    unitName: "Basınç",
    outcomeCode: "F.8.3.1.1",
    outcomeDescription: "Katı basıncını etkileyen değişkenleri deneyerek keşfeder.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.3",
    unitName: "Basınç",
    outcomeCode: "F.8.3.1.2",
    outcomeDescription: "Sıvı basıncını etkileyen değişkenleri tahmin eder ve tahminlerini test eder.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.3",
    unitName: "Basınç",
    outcomeCode: "F.8.3.1.3",
    outcomeDescription: "Katı, sıvı ve gazların basınç özelliklerinin günlük yaşam ve teknolojideki uygulamalarına örnekler verir.",
    officialHours: null,
    source: grade8Source,
  },

  // ==========================================
  // ÜNİTE 4: Madde ve Endüstri (F.8.4)
  // ==========================================
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.4",
    unitName: "Madde ve Endüstri",
    outcomeCode: "F.8.4.1.1",
    outcomeDescription: "Periyodik sistemde, grup ve periyotların nasıl oluşturulduğunu açıklar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.4",
    unitName: "Madde ve Endüstri",
    outcomeCode: "F.8.4.1.2",
    outcomeDescription: "Elementleri periyodik tablo üzerinde metal, yarımetal ve ametal olarak sınıflandırır.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.4",
    unitName: "Madde ve Endüstri",
    outcomeCode: "F.8.4.2.1",
    outcomeDescription: "Fiziksel ve kimyasal değişim arasındaki farkları, çeşitli olayları gözlemleyerek açıklar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.4",
    unitName: "Madde ve Endüstri",
    outcomeCode: "F.8.4.3.1",
    outcomeDescription: "Bileşiklerin kimyasal tepkime sonucunda oluştuğunu bilir.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.4",
    unitName: "Madde ve Endüstri",
    outcomeCode: "F.8.4.4.1",
    outcomeDescription: "Asit ve bazların genel özelliklerini ifade eder.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.4",
    unitName: "Madde ve Endüstri",
    outcomeCode: "F.8.4.4.2",
    outcomeDescription: "Asit ve bazlara günlük yaşamdan örnekler verir.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.4",
    unitName: "Madde ve Endüstri",
    outcomeCode: "F.8.4.4.3",
    outcomeDescription: "Günlük hayatta ulaşılabilecek malzemeleri asit-baz ayracı olarak kullanır.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.4",
    unitName: "Madde ve Endüstri",
    outcomeCode: "F.8.4.4.4",
    outcomeDescription: "Maddelerin asitlik ve bazlık durumlarına ilişkin pH değerlerini kullanarak çıkarımda bulunur.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.4",
    unitName: "Madde ve Endüstri",
    outcomeCode: "F.8.4.4.5",
    outcomeDescription: "Asit ve bazların çeşitli maddeler üzerindeki etkilerini gözlemler.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.4",
    unitName: "Madde ve Endüstri",
    outcomeCode: "F.8.4.4.6",
    outcomeDescription: "Asit ve bazların temizlik malzemesi olarak kullanılması esnasında oluşabilecek tehlikelerle ilgili gerekli tedbirleri alır.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.4",
    unitName: "Madde ve Endüstri",
    outcomeCode: "F.8.4.4.7",
    outcomeDescription: "Asit yağmurlarının önlenmesine yönelik çözüm önerileri sunar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.4",
    unitName: "Madde ve Endüstri",
    outcomeCode: "F.8.4.5.1",
    outcomeDescription: "Isınmanın maddenin cinsine, kütlesine ve/veya sıcaklık değişimine bağlı olduğunu deney yaparak keşfeder.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.4",
    unitName: "Madde ve Endüstri",
    outcomeCode: "F.8.4.5.2",
    outcomeDescription: "Hâl değiştirmek için gerekli ısının maddenin cinsi ve kütlesiyle ilişkili olduğunu deney yaparak keşfeder.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.4",
    unitName: "Madde ve Endüstri",
    outcomeCode: "F.8.4.5.3",
    outcomeDescription: "Maddelerin hâl değişimi ve ısınma grafiğini çizerek yorumlar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.4",
    unitName: "Madde ve Endüstri",
    outcomeCode: "F.8.4.5.4",
    outcomeDescription: "Günlük yaşamda meydana gelen hâl değişimleri ile ısı alışverişini ilişkilendirir.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.4",
    unitName: "Madde ve Endüstri",
    outcomeCode: "F.8.4.6.1",
    outcomeDescription: "Geçmişten günümüze Türkiye’deki kimya endüstrisinin gelişimini araştırır.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.4",
    unitName: "Madde ve Endüstri",
    outcomeCode: "F.8.4.6.2",
    outcomeDescription: "Kimya endüstrisinde meslek dallarını araştırır ve gelecekteki yeni meslek alanları hakkında öneriler sunar.",
    officialHours: null,
    source: grade8Source,
  },

  // ==========================================
  // ÜNİTE 5: Basit Makineler (F.8.5)
  // ==========================================
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.5",
    unitName: "Basit Makineler",
    outcomeCode: "F.8.5.1.1",
    outcomeDescription: "Basit makinelerin sağladığı avantajları örnekler üzerinden açıklar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.5",
    unitName: "Basit Makineler",
    outcomeCode: "F.8.5.1.2",
    outcomeDescription: "Basit makinelerden yararlanarak günlük yaşamda iş kolaylığı sağlayacak bir düzenek tasarlar.",
    officialHours: null,
    source: grade8Source,
  },

  // ==========================================
  // ÜNİTE 6: Enerji Dönüşümleri ve Çevre Bilimi (F.8.6)
  // ==========================================
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.6",
    unitName: "Enerji Dönüşümleri ve Çevre Bilimi",
    outcomeCode: "F.8.6.1.1",
    outcomeDescription: "Besin zincirindeki üretici, tüketici, ayrıştırıcılara örnekler verir.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.6",
    unitName: "Enerji Dönüşümleri ve Çevre Bilimi",
    outcomeCode: "F.8.6.2.1",
    outcomeDescription: "Bitkilerde besin üretiminde fotosentezin önemini fark eder.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.6",
    unitName: "Enerji Dönüşümleri ve Çevre Bilimi",
    outcomeCode: "F.8.6.2.2",
    outcomeDescription: "Fotosentez hızını etkileyen faktörler ile ilgili çıkarımlarda bulunur.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.6",
    unitName: "Enerji Dönüşümleri ve Çevre Bilimi",
    outcomeCode: "F.8.6.2.3",
    outcomeDescription: "Canlılarda solunumun önemini belirtir.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.6",
    unitName: "Enerji Dönüşümleri ve Çevre Bilimi",
    outcomeCode: "F.8.6.3.1",
    outcomeDescription: "Madde döngülerini şema üzerinde göstererek açıklar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.6",
    unitName: "Enerji Dönüşümleri ve Çevre Bilimi",
    outcomeCode: "F.8.6.3.2",
    outcomeDescription: "Madde döngülerinin yaşam açısından önemini sorgular.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.6",
    unitName: "Enerji Dönüşümleri ve Çevre Bilimi",
    outcomeCode: "F.8.6.3.3",
    outcomeDescription: "Küresel iklim değişikliklerinin nedenlerini ve olası sonuçlarını tartışır.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.6",
    unitName: "Enerji Dönüşümleri ve Çevre Bilimi",
    outcomeCode: "F.8.6.4.1",
    outcomeDescription: "Kaynakların kullanımında tasarruflu davranmaya özen gösterir.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.6",
    unitName: "Enerji Dönüşümleri ve Çevre Bilimi",
    outcomeCode: "F.8.6.4.2",
    outcomeDescription: "Kaynakların tasarruflu kullanımına yönelik proje tasarlar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.6",
    unitName: "Enerji Dönüşümleri ve Çevre Bilimi",
    outcomeCode: "F.8.6.4.3",
    outcomeDescription: "Geri dönüşüm için katı atıkların ayrıştırılmasının önemini açıklar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.6",
    unitName: "Enerji Dönüşümleri ve Çevre Bilimi",
    outcomeCode: "F.8.6.4.4",
    outcomeDescription: "Geri dönüşümün ülke ekonomisine katkısına ilişkin araştırma verilerini kullanarak çözüm önerileri sunar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.6",
    unitName: "Enerji Dönüşümleri ve Çevre Bilimi",
    outcomeCode: "F.8.6.4.5",
    outcomeDescription: "Kaynakların tasarruflu kullanılmaması durumunda gelecekte karşılaşılabilecek problemleri belirterek çözüm önerileri sunar.",
    officialHours: null,
    source: grade8Source,
  },

  // ==========================================
  // ÜNİTE 7: Elektrik Yükleri ve Elektrik Enerjisi (F.8.7)
  // ==========================================
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.7",
    unitName: "Elektrik Yükleri ve Elektrik Enerjisi",
    outcomeCode: "F.8.7.1.1",
    outcomeDescription: "Elektriklenmeyi, bazı doğa olayları ve teknolojideki uygulama örnekleri ile açıklar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.7",
    unitName: "Elektrik Yükleri ve Elektrik Enerjisi",
    outcomeCode: "F.8.7.1.2",
    outcomeDescription: "Elektrik yüklerini sınıflandırarak aynı ve farklı cins elektrik yüklerinin birbirlerine etkisini açıklar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.7",
    unitName: "Elektrik Yükleri ve Elektrik Enerjisi",
    outcomeCode: "F.8.7.1.3",
    outcomeDescription: "Deneyler yaparak elektriklenme çeşitlerini fark eder.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.7",
    unitName: "Elektrik Yükleri ve Elektrik Enerjisi",
    outcomeCode: "F.8.7.2.1",
    outcomeDescription: "Cisimleri, sahip oldukları elektrik yükleri bakımından sınıflandırır.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.7",
    unitName: "Elektrik Yükleri ve Elektrik Enerjisi",
    outcomeCode: "F.8.7.2.2",
    outcomeDescription: "Topraklamayı açıklar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.7",
    unitName: "Elektrik Yükleri ve Elektrik Enerjisi",
    outcomeCode: "F.8.7.3.1",
    outcomeDescription: "Elektrik enerjisinin ısı, ışık ve hareket enerjisine dönüştüğü uygulamalara örnekler verir.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.7",
    unitName: "Elektrik Yükleri ve Elektrik Enerjisi",
    outcomeCode: "F.8.7.3.2",
    outcomeDescription: "Elektirik enerjisinin ısı, ışık veya hareket enerjisine dönüşümü temel alan bir model tasarlar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.7",
    unitName: "Elektrik Yükleri ve Elektrik Enerjisi",
    outcomeCode: "F.8.7.3.3",
    outcomeDescription: "Güç santrallerinde elektrik enerjisinin nasıl üretildiğini açıklar.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.7",
    unitName: "Elektrik Yükleri ve Elektrik Enerjisi",
    outcomeCode: "F.8.7.3.4",
    outcomeDescription: "Güç santrallerinin avantaj ve dezavantajları konusunda fikirler üretir.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.7",
    unitName: "Elektrik Yükleri ve Elektrik Enerjisi",
    outcomeCode: "F.8.7.3.5",
    outcomeDescription: "Elektrik enerjisinin bilinçli ve tasarruflu kullanılmasının aile ve ülke ekonomisi bakımından önemini tartışır.",
    officialHours: null,
    source: grade8Source,
  },
  {
    grade: 8,
    curriculumFamily: "fen-2018",
    unitCode: "F.8.7",
    unitName: "Elektrik Yükleri ve Elektrik Enerjisi",
    outcomeCode: "F.8.7.3.6",
    outcomeDescription: "Evlerde elektriği tasarruflu kullanmaya özen gösterir.",
    officialHours: null,
    source: grade8Source,
  },
] as const;
