import type { CurriculumOutcomeMetadata } from "./types";

export const grade7CurriculumMetadata: readonly CurriculumOutcomeMetadata[] = [
  // ==========================================
  // ÜNİTE 1: Uzay Çağı (FB.7.1)
  // ==========================================
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.1",
    unitName: "Uzay Çağı",
    outcomeCode: "FB.7.1.1.1",
    outcomeDescription: "Uzay araştırmaları için geliştirilen teknolojileri karşılaştırabilme",
    officialHours: null,
    processComponents: [
      "a) Uzay araştırmaları için geliştirilen teknolojilerin özelliklerini belirler.",
      "b) Uzay araştırmaları için geliştirilen teknolojilerin özelliklerine göre benzerliklerini listeler.",
      "c) Uzay araştırmaları için geliştirilen teknolojilerin özelliklerine göre farklılıklarını listeler.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/416",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.1",
    unitName: "Uzay Çağı",
    outcomeCode: "FB.7.1.1.2",
    outcomeDescription: "Uzay gözlem araçları ile ilgili bilimsel model oluşturabilme",
    officialHours: null,
    processComponents: [
      "a) Uzay gözlem araçları ile ilgili model önerir.",
      "b) Uzay gözlem araçları ile ilgili hazırladığı modeli yeni kanıtlara göre yeniler.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/416",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.1",
    unitName: "Uzay Çağı",
    outcomeCode: "FB.7.1.1.3",
    outcomeDescription: "Uzay araştırmalarının yol açabileceği problemleri çözebilme",
    officialHours: null,
    processComponents: [
      "a) Uzay araştırmalarının yol açabileceği problemleri yapılandırır.",
      "b) Uzay araştırmalarının yol açabileceği problemleri özetler.",
      "c) Uzay araştırmalarının yol açabileceği problemlerin çözümüne yönelik veriye dayalı tahminde bulunur.",
      "ç) Uzay araştırmalarının yol açabileceği problemlerin çözümüne yönelik önermeler üzerinden akıl yürütür.",
      "d) Uzay araştırmalarının yol açabileceği problemlerin çözümüne ilişkin değerlendirmede bulunur.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/416",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.1",
    unitName: "Uzay Çağı",
    outcomeCode: "FB.7.1.2.1",
    outcomeDescription: "Yıldızların yaşamını açıklayarak yapılandırabilme",
    officialHours: null,
    processComponents: [
      "a) Yıldızların yaşamını inceleyerek hiyerarşik ilişkileri ortaya koyar.",
      "b) Yıldızların yaşamı ile ilgili elde ettiği ilişkilere dayalı unsurlardan uyumlu bir bütün oluşturur.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/416",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.1",
    unitName: "Uzay Çağı",
    outcomeCode: "FB.7.1.2.2",
    outcomeDescription: "Yıldız, galaksi ve evren kavramlarını açıklayarak yapılandırabilme",
    officialHours: null,
    processComponents: [
      "a) Yıldız, galaksi ve evren kavramlarını inceleyerek hiyerarşik ilişkileri ortaya koyar.",
      "b) Yıldız, galaksi ve evren kavramları ile ilgili elde ettiği ilişkilere dayalı unsurlardan uyumlu bir bütün oluşturur.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/416",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },

  // ==========================================
  // ÜNİTE 2: Kuvvet ve Enerjiyi Keşfedelim (FB.7.2)
  // ==========================================
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.2",
    unitName: "Kuvvet ve Enerjiyi Keşfedelim",
    outcomeCode: "FB.7.2.1.1",
    outcomeDescription: "Fiziksel anlamda yapılan işin bağlı olduğu faktörlere ilişkin bilimsel çıkarım yapabilme",
    officialHours: null,
    processComponents: [
      "a) Fiziksel anlamda yapılan işin niteliklerini tanımlar.",
      "b) Fiziksel anlamda yapılan işin farklı örneklerini gözlemleyerek verileri toplar ve kaydeder.",
      "c) Fiziksel anlamda yapılan işin kuvvet ve yer değiştirmeye bağlı olduğunu yorumlar ve değerlendirir.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/429",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.2",
    unitName: "Kuvvet ve Enerjiyi Keşfedelim",
    outcomeCode: "FB.7.2.1.2",
    outcomeDescription: "Enerji çeşitlerinden kinetik ve potansiyel enerjiyi karşılaştırabilme",
    officialHours: null,
    processComponents: [
      "a) Kinetik ve potansiyel enerjinin özelliklerini belirler.",
      "b) Kinetik ve potansiyel enerjinin benzer özelliklerini listeler.",
      "c) Kinetik ve potansiyel enerjinin farklı özelliklerini listeler.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/429",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.2",
    unitName: "Kuvvet ve Enerjiyi Keşfedelim",
    outcomeCode: "FB.7.2.2.1",
    outcomeDescription: "Enerji dönüşümünden hareketle enerjinin korunduğuna tümevarımsal akıl yürütebilme",
    officialHours: null,
    processComponents: [
      "a) Kinetik ve potansiyel enerjinin birbirine dönüşümüne yönelik örüntü bulur.",
      "b) Enerjinin korunumuna yönelik genelleme yapar.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/429",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },

  // ==========================================
  // ÜNİTE 3: Vücudumuzdaki Sistemler (FB.7.3)
  // ==========================================
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.3",
    unitName: "Vücudumuzdaki Sistemler",
    outcomeCode: "FB.7.3.1.1",
    outcomeDescription: "Sindirim sistemini oluşturan yapı ve organların görevlerini model üzerinde gözlemleyebilme",
    officialHours: null,
    processComponents: [
      "a) Sindirim sistemini oluşturan yapı ve organların niteliklerini tanımlar.",
      "b) Sindirim sistemini oluşturan yapı ve organları model üzerinde inceleyerek gözlem verilerini kaydeder.",
      "c) Sindirim sistemini oluşturan yapı ve organların görevlerini açıklar.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/430",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.3",
    unitName: "Vücudumuzdaki Sistemler",
    outcomeCode: "FB.7.3.1.2",
    outcomeDescription: "Sindirim sisteminin sağlığı için yapılması gerekenler konusunda bilgi toplayabilme",
    officialHours: null,
    processComponents: [
      "a) Sindirim sisteminin sağlığı ile ilgili bilgiye ulaşmak için kullanacağı araçları belirler.",
      "b) Belirlediği araçları kullanarak sindirim sisteminin sağlığı hakkında bilgiler bulur.",
      "c) Sindirim sisteminin sağlığı hakkında bulduğu bilgileri doğrular.",
      "ç) Sindirim sisteminin sağlığı hakkında bulduğu bilgileri kaydeder.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/430",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.3",
    unitName: "Vücudumuzdaki Sistemler",
    outcomeCode: "FB.7.3.2.1",
    outcomeDescription: "Dolaşım sistemini oluşturan yapı ve organların görevlerini model üzerinde gözlemleyebilme",
    officialHours: null,
    processComponents: [
      "a) Dolaşım sistemini oluşturan yapı ve organların niteliklerini tanımlar.",
      "b) Dolaşım sistemini oluşturan yapı ve organları model üzerinde inceleyerek gözlem verilerini kaydeder.",
      "c) Dolaşım sistemini oluşturan yapı ve organların görevlerini açıklar.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/430",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.3",
    unitName: "Vücudumuzdaki Sistemler",
    outcomeCode: "FB.7.3.2.2",
    outcomeDescription: "Kan bağışının toplumsal dayanışma açısından önemini tartışabilme",
    officialHours: null,
    processComponents: [
      "a) Kan bağışının toplumsal dayanışma açısından önemine yönelik mantıksal temellendirme yapar.",
      "b) Kan bağışının toplumsal dayanışma açısından önemine yönelik mantıksal çelişkileri tespit eder.",
      "c) Kan bağışının toplumsal dayanışma açısından önemi konusunda geçerli fikirler oluşturur.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/430",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.3",
    unitName: "Vücudumuzdaki Sistemler",
    outcomeCode: "FB.7.3.2.3",
    outcomeDescription: "Dolaşım sisteminin sağlığı için yapılması gerekenler konusunda bilgi toplayabilme",
    officialHours: null,
    processComponents: [
      "a) Dolaşım sisteminin sağlığı ile ilgili bilgiye ulaşmak için kullanacağı araçları belirler.",
      "b) Belirlediği aracı kullanarak dolaşım sisteminin sağlığı hakkında bilgiler bulur.",
      "c) Dolaşım sisteminin sağlığı hakkında bulduğu bilgileri doğrular.",
      "ç) Dolaşım sisteminin sağlığı hakkında bulduğu bilgileri kaydeder.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/430",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.3",
    unitName: "Vücudumuzdaki Sistemler",
    outcomeCode: "FB.7.3.3.1",
    outcomeDescription: "Solunum sistemini oluşturan yapı ve organların görevlerini model üzerinde gözlemleyebilme",
    officialHours: null,
    processComponents: [
      "a) Solunum sistemini oluşturan yapı ve organların niteliklerini tanımlar.",
      "b) Solunum sistemini oluşturan yapı ve organları model üzerinde inceleyerek gözlem verilerini kaydeder.",
      "c) Solunum sistemini oluşturan yapı ve organların görevlerini açıklar.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/430",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.3",
    unitName: "Vücudumuzdaki Sistemler",
    outcomeCode: "FB.7.3.3.2",
    outcomeDescription: "Solunum sisteminin sağlığı için yapılması gerekenler konusunda bilgi toplayabilme",
    officialHours: null,
    processComponents: [
      "a) Solunum sisteminin sağlığı ile ilgili bilgiye ulaşmak için kullanacağı araçları belirler.",
      "b) Belirlediği aracı kullanarak solunum sisteminin sağlığı hakkında bilgiler bulur.",
      "c) Solunum sisteminin sağlığı hakkında bulduğu bilgileri doğrular.",
      "ç) Solunum sisteminin sağlığı hakkında bulduğu bilgileri kaydeder.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/430",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.3",
    unitName: "Vücudumuzdaki Sistemler",
    outcomeCode: "FB.7.3.4.1",
    outcomeDescription: "Boşaltım sistemini oluşturan yapı ve organları model üzerinde gözlemleyebilme",
    officialHours: null,
    processComponents: [
      "a) Boşaltım sistemini oluşturan yapı ve organların niteliklerini tanımlar.",
      "b) Boşaltım sistemini oluşturan yapı ve organları model üzerinde inceleyerek gözlem verilerini kaydeder.",
      "c) Boşaltım sistemini oluşturan yapı ve organların özelliklerini açıklar.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/430",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.3",
    unitName: "Vücudumuzdaki Sistemler",
    outcomeCode: "FB.7.3.4.2",
    outcomeDescription: "Boşaltım sisteminin sağlığı için yapılması gerekenler konusunda bilgi toplayabilme",
    officialHours: null,
    processComponents: [
      "a) Boşaltım sisteminin sağlığı ile ilgili bilgiye ulaşmak için kullanacağı araçları belirler.",
      "b) Belirlediği aracı kullanarak boşaltım sisteminin sağlığı hakkında bilgiler bulur.",
      "c) Boşaltım sisteminin sağlığı hakkında bulduğu bilgileri doğrular.",
      "ç) Boşaltım sisteminin sağlığı hakkında ulaştığı bilgileri kaydeder.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/430",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },

  // ==========================================
  // ÜNİTE 4: Işığın Kırılması ve Mercekler (FB.7.4)
  // ==========================================
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.4",
    unitName: "Işığın Kırılması ve Mercekler",
    outcomeCode: "FB.7.4.1.1",
    outcomeDescription: "Ortam değiştiren ışığın izlediği yolu gözlemleyerek kırılma olayına yönelik bilimsel çıkarım yapabilme",
    officialHours: null,
    processComponents: [
      "a) Işık ışınlarının kırılmasına yönelik nitelikleri tanımlar.",
      "b) Farklı yoğunluklara sahip ortamlarda ışığın kırılmasına yönelik verileri toplayarak kaydeder.",
      "c) Az yoğun ortamda ve çok yoğun ortamda ışığın izlediği yolları yorumlar ve değerlendirir.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/431",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.4",
    unitName: "Işığın Kırılması ve Mercekler",
    outcomeCode: "FB.7.4.2.1",
    outcomeDescription: "Mercek çeşitlerine yönelik bilimsel çıkarım yapabilme",
    officialHours: null,
    processComponents: [
      "a) Mercek çeşitlerinin niteliklerini deneyerek tanımlar.",
      "b) Mercek çeşitlerini kullanarak özelliklerine yönelik veri kaydeder.",
      "c) Mercekleri ince ve kalın kenarlı mercek olarak yorumlar ve değerlendirir.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/431",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.4",
    unitName: "Işığın Kırılması ve Mercekler",
    outcomeCode: "FB.7.4.2.2",
    outcomeDescription: "Merceklerin günlük hayatta kullanım alanlarını örneklerle sınıflandırabilme",
    officialHours: null,
    processComponents: [
      "a) Merceklerin kullanım alanlarını belirler.",
      "b) Merceklerin kullanım alanlarını niteliklerine göre ayrıştırır.",
      "c) Merceklerin kullanım alanlarını gruplandırır.",
      "ç) Merceklerin kullanım alanlarını niteliklerine göre etiketler.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/431",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },

  // ==========================================
  // ÜNİTE 5: Maddenin Doğasına Yolculuk (FB.7.5)
  // ==========================================
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.5",
    unitName: "Maddenin Doğasına Yolculuk",
    outcomeCode: "FB.7.5.1.1",
    outcomeDescription: "Atomun yapısını ve yapısındaki temel parçacıkları çözümleyebilme",
    officialHours: null,
    processComponents: [
      "a) Atomu oluşturan temel parçacıkları belirler.",
      "b) Atomu oluşturan temel parçacıklar arasındaki ilişkileri belirler.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/432",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.5",
    unitName: "Maddenin Doğasına Yolculuk",
    outcomeCode: "FB.7.5.1.2",
    outcomeDescription: "Geçmişten günümüze atom kavramı ile ilgili bilimsel bilgilerin değişebileceğini sorgulayabilme",
    officialHours: null,
    processComponents: [
      "a) Geçmişten günümüze atomun sürecini açıklar.",
      "b) Geçmişten günümüze atom ile ilgili sorular sorar.",
      "c) Geçmişten günümüze atom ile ilgili bilgi toplar.",
      "ç) Toplanan bilgilerin doğruluğunu değerlendirir.",
      "d) Toplanan bilgiler üzerinde çıkarım yapar.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/432",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.5",
    unitName: "Maddenin Doğasına Yolculuk",
    outcomeCode: "FB.7.5.1.3",
    outcomeDescription: "Farklı moleküllere ait bilimsel model oluşturabilme",
    officialHours: null,
    processComponents: [
      "a) Aynı veya farklı atomların bir araya gelmesiyle ilgili molekül modeli önerir.",
      "b) Yeni kanıtlarla modeli yeniler.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/432",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.5",
    unitName: "Maddenin Doğasına Yolculuk",
    outcomeCode: "FB.7.5.1.4",
    outcomeDescription: "Atomların elektron dizilimlerini yapılandırabilme",
    officialHours: null,
    processComponents: [
      "a) Atomların elektron dizilimlerine ilişkin hiyerarşik ilişkileri ortaya koyar.",
      "b) Atomların elektron dizilimlerine ilişkin elde ettiği bilgileri uyumlu bir bütün olarak ortaya koyar.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/432",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.5",
    unitName: "Maddenin Doğasına Yolculuk",
    outcomeCode: "FB.7.5.2.1",
    outcomeDescription: "Saf maddeleri element ve bileşik olarak sınıflandırabilme",
    officialHours: null,
    processComponents: [
      "a) Saf maddelerin farklı yapıda olduğunu belirler.",
      "b) Saf maddeleri niteliklerine göre ayrıştırır.",
      "c) Saf maddeleri element ve bileşik olarak sınıflar.",
      "ç) Çevresindeki maddeleri element ve bileşik olarak etiketlendirir.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/432",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.5",
    unitName: "Maddenin Doğasına Yolculuk",
    outcomeCode: "FB.7.5.2.2",
    outcomeDescription: "Periyodik tablodaki ilk 18 elementin isimlerini sembolleriyle yapılandırabilme",
    officialHours: null,
    processComponents: [
      "a) Periyodik tablodaki ilk 18 elementin isimlerini ve sembollerini inceleyerek mantıksal ilişkiler ortaya koyar.",
      "b) Konu ile ilgili ön öğrenmelerine bağlı olarak uyumlu bir bütün oluşturur.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/432",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.5",
    unitName: "Maddenin Doğasına Yolculuk",
    outcomeCode: "FB.7.5.2.3",
    outcomeDescription: "Periyodik tabloda grup ve periyotları karşılaştırabilme",
    officialHours: null,
    processComponents: [
      "a) Periyodik tabloda grup ve periyotlara ilişkin özellikleri belirler.",
      "b) Belirlenen özelliklere ilişkin benzerlikleri listeler.",
      "c) Belirlenen özelliklere ilişkin farklılıkları listeler.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/432",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.5",
    unitName: "Maddenin Doğasına Yolculuk",
    outcomeCode: "FB.7.5.2.4",
    outcomeDescription: "Bileşiklerin isimlerini formülleriyle yapılandırabilme",
    officialHours: null,
    processComponents: [
      "a) Yaygın kullanılan bileşiklerin formüllerini inceleyerek mantıksal ilişkiler ortaya koyar.",
      "b) Konu ile ilgili ön öğrenmelerine bağlı olarak uyumlu bir bütün oluşturur.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/432",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.5",
    unitName: "Maddenin Doğasına Yolculuk",
    outcomeCode: "FB.7.5.3.1",
    outcomeDescription: "Karışımları homojen ve heterojen olarak sınıflandırabilme",
    officialHours: null,
    processComponents: [
      "a) Karışımların görünümlerinin farklı yapıda olduğunu belirler.",
      "b) Farklı görünümlerdeki karışımları niteliklerine göre ayrıştırır.",
      "c) Karışımları homojen ve heterojen olarak gruplandırır.",
      "ç) Çevresindeki maddeleri homojen ve heterojen karışım olarak etiketler.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/432",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.5",
    unitName: "Maddenin Doğasına Yolculuk",
    outcomeCode: "FB.7.5.3.2",
    outcomeDescription: "Çözünme hızına etki eden faktörler ile ilgili hipotez oluşturabilme",
    officialHours: null,
    processComponents: [
      "a) Çözünme hızını etkileyen faktörleri tanımlar.",
      "b) Çözünme hızı ile onu etkileyen faktörler arasındaki neden sonuç ilişkilerini belirler.",
      "c) Çözünme hızını etkileyen değişkenleri belirler.",
      "ç) Temas yüzeyi, karıştırma ve sıcaklık değişkenlerini kontrol eder.",
      "d) Çözünme hızını etkileyen faktörlere ait önermeler sunar.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/432",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.5",
    unitName: "Maddenin Doğasına Yolculuk",
    outcomeCode: "FB.7.5.4.1",
    outcomeDescription: "Karışımları ayırmak için çeşitli deney yapabilme",
    officialHours: null,
    processComponents: [
      "a) Farklı karışımları ayırmak için deney tasarlar.",
      "b) Deney ile ilgili ölçme ve veri analizi yapar.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/432",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },

  // ==========================================
  // ÜNİTE 6: Elektriklenme (FB.7.6)
  // ==========================================
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.6",
    unitName: "Elektriklenme",
    outcomeCode: "FB.7.6.1.1",
    outcomeDescription: "Elektriklenme ile ilgili bilgi toplayabilme",
    officialHours: null,
    processComponents: [
      "a) Elektriklenme ile ilgili bilgiye ulaşmak için kullanacağı araçları belirler.",
      "b) Belirlediği araçları kullanarak elektriklenme hakkında bilgileri bulur.",
      "c) Elektriklenme ile ilgili bulduğu bilgileri doğrular.",
      "ç) Elektriklenme ile ilgili bulduğu bilgileri kaydeder.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/433",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.6",
    unitName: "Elektriklenme",
    outcomeCode: "FB.7.6.1.2",
    outcomeDescription: "Elektriklenme çeşitlerini belirlemeye yönelik deney yapabilme",
    officialHours: null,
    processComponents: [
      "a) Elektriklenme çeşitlerini gözlemleyebilecekleri bir deney tasarlar.",
      "b) Deneyle ilgili ölçme ve veri analizi yapar.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/433",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.6",
    unitName: "Elektriklenme",
    outcomeCode: "FB.7.6.1.3",
    outcomeDescription: "Cisimlerin elektrik yüklerini sınıflandırabilme",
    officialHours: null,
    processComponents: [
      "a) Cisimlerin elektrik yüklerinin niteliklerini belirler.",
      "b) Cisimlerin yük durumlarını ayrıştırır.",
      "c) Cisimlerin yük durumlarını gruplandırır.",
      "ç) Cisimlerin yük durumlarını negatif, pozitif ve nötr olarak etiketler.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/433",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },

  // ==========================================
  // ÜNİTE 7: Sürdürülebilir Yaşam ve Enerji (FB.7.7)
  // ==========================================
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.7",
    unitName: "Sürdürülebilir Yaşam ve Enerji",
    outcomeCode: "FB.7.7.1.1",
    outcomeDescription: "Besin zincirindeki canlılar arasındaki ilişkileri yapılandırabilme",
    officialHours: null,
    processComponents: [
      "a) Besin zincirindeki canlılar arasındaki nedensel ilişkileri ortaya koyar.",
      "b) Besin zincirini uyumlu bir bütün olarak açıklar.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/434",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
  {
    grade: 7,
    curriculumFamily: "maarif",
    unitCode: "FB.7.7",
    unitName: "Sürdürülebilir Yaşam ve Enerji",
    outcomeCode: "FB.7.7.2.1",
    outcomeDescription: "Kaynakların tasarruflu kullanımının önemini sorgulayabilme",
    officialHours: null,
    processComponents: [
      "a) Kaynakların tasarruflu kullanımı ile ilgili problemi tanımlar.",
      "b) Kaynakların tasarruflu kullanımına yönelik çözüm bulmak için model geliştirir.",
      "c) Kaynakların tasarruflu kullanımına yönelik planladığı araştırmayı gerçekleştirir.",
      "ç) Kaynakların tasarruflu kullanımına yönelik analiz ettiği verileri yorumlar.",
      "d) Kaynakların tasarruflu kullanımına yönelik kanıta dayalı çözüm üretir.",
      "e) Kaynakların tasarruflu kullanımına yönelik bilgileri değerlendirir ve paylaşır.",
    ],
    source: {
      title: "Türkiye Yüzyılı Maarif Modeli Fen Bilimleri Dersi Öğretim Programı",
      url: "https://tymm.meb.gov.tr/fen-bilimleri-dersi/unite/434",
      documentName: "2024programfen345678Onayli.pdf",
    },
  },
] as const;
